/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ricoh.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Registro service. Represents a row in the &quot;agu_Registro&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ricoh.model.impl.RegistroModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ricoh.model.impl.RegistroImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Registro
 * @generated
 */
@ProviderType
public interface RegistroModel extends BaseModel<Registro> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a registro model instance should use the {@link Registro} interface instead.
	 */

	/**
	 * Returns the primary key of this registro.
	 *
	 * @return the primary key of this registro
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this registro.
	 *
	 * @param primaryKey the primary key of this registro
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this registro.
	 *
	 * @return the uuid of this registro
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this registro.
	 *
	 * @param uuid the uuid of this registro
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the registro ID of this registro.
	 *
	 * @return the registro ID of this registro
	 */
	public long getRegistroId();

	/**
	 * Sets the registro ID of this registro.
	 *
	 * @param registroId the registro ID of this registro
	 */
	public void setRegistroId(long registroId);

	/**
	 * Returns the nombre of this registro.
	 *
	 * @return the nombre of this registro
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this registro.
	 *
	 * @param nombre the nombre of this registro
	 */
	public void setNombre(String nombre);

	/**
	 * Returns the apellido of this registro.
	 *
	 * @return the apellido of this registro
	 */
	@AutoEscape
	public String getApellido();

	/**
	 * Sets the apellido of this registro.
	 *
	 * @param apellido the apellido of this registro
	 */
	public void setApellido(String apellido);

	/**
	 * Returns the nacimiento of this registro.
	 *
	 * @return the nacimiento of this registro
	 */
	public Date getNacimiento();

	/**
	 * Sets the nacimiento of this registro.
	 *
	 * @param nacimiento the nacimiento of this registro
	 */
	public void setNacimiento(Date nacimiento);

	/**
	 * Returns the correo of this registro.
	 *
	 * @return the correo of this registro
	 */
	@AutoEscape
	public String getCorreo();

	/**
	 * Sets the correo of this registro.
	 *
	 * @param correo the correo of this registro
	 */
	public void setCorreo(String correo);

	/**
	 * Returns the fechacreacion of this registro.
	 *
	 * @return the fechacreacion of this registro
	 */
	public Date getFechacreacion();

	/**
	 * Sets the fechacreacion of this registro.
	 *
	 * @param fechacreacion the fechacreacion of this registro
	 */
	public void setFechacreacion(Date fechacreacion);

	@Override
	public Registro cloneWithOriginalValues();

}