/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ricoh.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.ricoh.model.Registro;
import com.ricoh.model.RegistroModel;
import com.ricoh.model.RegistroSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Registro service. Represents a row in the &quot;agu_Registro&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>RegistroModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RegistroImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RegistroImpl
 * @generated
 */
@JSON(strict = true)
public class RegistroModelImpl
	extends BaseModelImpl<Registro> implements RegistroModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a registro model instance should use the <code>Registro</code> interface instead.
	 */
	public static final String TABLE_NAME = "agu_Registro";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"registroId", Types.BIGINT},
		{"nombre", Types.VARCHAR}, {"apellido", Types.VARCHAR},
		{"nacimiento", Types.TIMESTAMP}, {"correo", Types.VARCHAR},
		{"fechacreacion", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("registroId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("nombre", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("apellido", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nacimiento", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("correo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fechacreacion", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table agu_Registro (uuid_ VARCHAR(75) null,registroId LONG not null primary key,nombre VARCHAR(75) null,apellido VARCHAR(75) null,nacimiento DATE null,correo VARCHAR(75) null,fechacreacion DATE null)";

	public static final String TABLE_SQL_DROP = "drop table agu_Registro";

	public static final String ORDER_BY_JPQL =
		" ORDER BY registro.registroId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY agu_Registro.registroId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long REGISTROID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static Registro toModel(RegistroSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Registro model = new RegistroImpl();

		model.setUuid(soapModel.getUuid());
		model.setRegistroId(soapModel.getRegistroId());
		model.setNombre(soapModel.getNombre());
		model.setApellido(soapModel.getApellido());
		model.setNacimiento(soapModel.getNacimiento());
		model.setCorreo(soapModel.getCorreo());
		model.setFechacreacion(soapModel.getFechacreacion());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<Registro> toModels(RegistroSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Registro> models = new ArrayList<Registro>(soapModels.length);

		for (RegistroSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public RegistroModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _registroId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setRegistroId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _registroId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Registro.class;
	}

	@Override
	public String getModelClassName() {
		return Registro.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Registro, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Registro, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Registro, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Registro)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Registro, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Registro, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Registro)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Registro, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Registro, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Registro>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Registro.class.getClassLoader(), Registro.class,
			ModelWrapper.class);

		try {
			Constructor<Registro> constructor =
				(Constructor<Registro>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Registro, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Registro, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Registro, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Registro, Object>>();
		Map<String, BiConsumer<Registro, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Registro, ?>>();

		attributeGetterFunctions.put("uuid", Registro::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Registro, String>)Registro::setUuid);
		attributeGetterFunctions.put("registroId", Registro::getRegistroId);
		attributeSetterBiConsumers.put(
			"registroId", (BiConsumer<Registro, Long>)Registro::setRegistroId);
		attributeGetterFunctions.put("nombre", Registro::getNombre);
		attributeSetterBiConsumers.put(
			"nombre", (BiConsumer<Registro, String>)Registro::setNombre);
		attributeGetterFunctions.put("apellido", Registro::getApellido);
		attributeSetterBiConsumers.put(
			"apellido", (BiConsumer<Registro, String>)Registro::setApellido);
		attributeGetterFunctions.put("nacimiento", Registro::getNacimiento);
		attributeSetterBiConsumers.put(
			"nacimiento", (BiConsumer<Registro, Date>)Registro::setNacimiento);
		attributeGetterFunctions.put("correo", Registro::getCorreo);
		attributeSetterBiConsumers.put(
			"correo", (BiConsumer<Registro, String>)Registro::setCorreo);
		attributeGetterFunctions.put(
			"fechacreacion", Registro::getFechacreacion);
		attributeSetterBiConsumers.put(
			"fechacreacion",
			(BiConsumer<Registro, Date>)Registro::setFechacreacion);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getRegistroId() {
		return _registroId;
	}

	@Override
	public void setRegistroId(long registroId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_registroId = registroId;
	}

	@JSON
	@Override
	public String getNombre() {
		if (_nombre == null) {
			return "";
		}
		else {
			return _nombre;
		}
	}

	@Override
	public void setNombre(String nombre) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nombre = nombre;
	}

	@JSON
	@Override
	public String getApellido() {
		if (_apellido == null) {
			return "";
		}
		else {
			return _apellido;
		}
	}

	@Override
	public void setApellido(String apellido) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_apellido = apellido;
	}

	@JSON
	@Override
	public Date getNacimiento() {
		return _nacimiento;
	}

	@Override
	public void setNacimiento(Date nacimiento) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nacimiento = nacimiento;
	}

	@JSON
	@Override
	public String getCorreo() {
		if (_correo == null) {
			return "";
		}
		else {
			return _correo;
		}
	}

	@Override
	public void setCorreo(String correo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_correo = correo;
	}

	@JSON
	@Override
	public Date getFechacreacion() {
		return _fechacreacion;
	}

	@Override
	public void setFechacreacion(Date fechacreacion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fechacreacion = fechacreacion;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Registro.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Registro toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Registro>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RegistroImpl registroImpl = new RegistroImpl();

		registroImpl.setUuid(getUuid());
		registroImpl.setRegistroId(getRegistroId());
		registroImpl.setNombre(getNombre());
		registroImpl.setApellido(getApellido());
		registroImpl.setNacimiento(getNacimiento());
		registroImpl.setCorreo(getCorreo());
		registroImpl.setFechacreacion(getFechacreacion());

		registroImpl.resetOriginalValues();

		return registroImpl;
	}

	@Override
	public Registro cloneWithOriginalValues() {
		RegistroImpl registroImpl = new RegistroImpl();

		registroImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		registroImpl.setRegistroId(
			this.<Long>getColumnOriginalValue("registroId"));
		registroImpl.setNombre(this.<String>getColumnOriginalValue("nombre"));
		registroImpl.setApellido(
			this.<String>getColumnOriginalValue("apellido"));
		registroImpl.setNacimiento(
			this.<Date>getColumnOriginalValue("nacimiento"));
		registroImpl.setCorreo(this.<String>getColumnOriginalValue("correo"));
		registroImpl.setFechacreacion(
			this.<Date>getColumnOriginalValue("fechacreacion"));

		return registroImpl;
	}

	@Override
	public int compareTo(Registro registro) {
		long primaryKey = registro.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Registro)) {
			return false;
		}

		Registro registro = (Registro)object;

		long primaryKey = registro.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Registro> toCacheModel() {
		RegistroCacheModel registroCacheModel = new RegistroCacheModel();

		registroCacheModel.uuid = getUuid();

		String uuid = registroCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			registroCacheModel.uuid = null;
		}

		registroCacheModel.registroId = getRegistroId();

		registroCacheModel.nombre = getNombre();

		String nombre = registroCacheModel.nombre;

		if ((nombre != null) && (nombre.length() == 0)) {
			registroCacheModel.nombre = null;
		}

		registroCacheModel.apellido = getApellido();

		String apellido = registroCacheModel.apellido;

		if ((apellido != null) && (apellido.length() == 0)) {
			registroCacheModel.apellido = null;
		}

		Date nacimiento = getNacimiento();

		if (nacimiento != null) {
			registroCacheModel.nacimiento = nacimiento.getTime();
		}
		else {
			registroCacheModel.nacimiento = Long.MIN_VALUE;
		}

		registroCacheModel.correo = getCorreo();

		String correo = registroCacheModel.correo;

		if ((correo != null) && (correo.length() == 0)) {
			registroCacheModel.correo = null;
		}

		Date fechacreacion = getFechacreacion();

		if (fechacreacion != null) {
			registroCacheModel.fechacreacion = fechacreacion.getTime();
		}
		else {
			registroCacheModel.fechacreacion = Long.MIN_VALUE;
		}

		return registroCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Registro, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Registro, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Registro, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Registro)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Registro, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Registro, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Registro, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Registro)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Registro>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _registroId;
	private String _nombre;
	private String _apellido;
	private Date _nacimiento;
	private String _correo;
	private Date _fechacreacion;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Registro, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Registro)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("registroId", _registroId);
		_columnOriginalValues.put("nombre", _nombre);
		_columnOriginalValues.put("apellido", _apellido);
		_columnOriginalValues.put("nacimiento", _nacimiento);
		_columnOriginalValues.put("correo", _correo);
		_columnOriginalValues.put("fechacreacion", _fechacreacion);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("registroId", 2L);

		columnBitmasks.put("nombre", 4L);

		columnBitmasks.put("apellido", 8L);

		columnBitmasks.put("nacimiento", 16L);

		columnBitmasks.put("correo", 32L);

		columnBitmasks.put("fechacreacion", 64L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Registro _escapedModel;

}